#
# TODO: TO be documented that we must configure such security rules on openshift
# oc adm policy add-scc-to-user privileged -z build-bot
# oc adm policy add-role-to-user edit -z build-bot
#
#
apiVersion: devexp.runtime.redhat.com/v1alpha2
kind: Component
metadata:
  name: fruit-backend-sb
spec:
  deploymentMode: build
  port: 8080
  buildConfig:
    url: https://github.com/snowdrop/component-operator-demo.git
    ref: master
    moduleDirName: fruit-backend-sb
  runtime: spring-boot
  version: 2.1.3
  envs:
  - name: SPRING_PROFILES_ACTIVE
    value: postgresql-kubedb