---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "fruit-client-sb"
    name: "fruit-client-sb"
  spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    exposeService: true
    buildConfig:
      type: "s2i"
      url: "https://github.com/halkyonio/operator.git"
      ref: "master"
      contextPath: "demo/"
      moduleDirName: "fruit-client-sb"
    port: 8080
    capabilities:
      requires:
        - name: backend
          boundTo: fruits-endpoint
          spec:
            category: api
            type: rest-component
            parameters:
              - name: halkyon.endpointKey
                value: KUBERNETES_ENDPOINT_FRUIT