kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: component-operator-role-binding
subjects:
  - kind: ServiceAccount
    name: component-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: component-operator
  apiGroup: rbac.authorization.k8s.io