kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: halkyon-operator
rules:
- apiGroups:
  - halkyon.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: halkyon-operator
subjects:
- kind: ServiceAccount
  name: halkyon-operator
roleRef:
  kind: Role
  name: halkyon-operator
  apiGroup: rbac.authorization.k8s.io
