server:
  port: 8080

# Endpoint property to access the backend microservice
endpoint:
  fruit: ${KUBERNETES_ENDPOINT_FRUIT}

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    name: fruit-client-sb
    deploymentMode: dev
    exposeService: true