server:
  port: 8080

# Endpoint property to access the backend microservice
endpoint:
  fruit: ${KUBERNETES_ENDPOINT_FRUIT}

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    name: fruit-client-sb
    deploymentMode: dev
    exposeService: true
  link:
    name: link-to-fruit-backend
    componentName: fruit-client-sb
    type: Env
    envs:
    - name: ENDPOINT_BACKEND
      value: http://fruit-backend-sb:8080/api/fruits
