apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: http-rest-sb
spec:
  deploymentMode: build
  exposeService: true
  port: 8080
  buildConfig:
    type: s2i
    url: https://github.com/snowdrop/rest-http-example.git
    ref: 2.1.6-4
    moduleDirName: .
  runtime: spring-boot
  version: 2.1.6
