apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: capabilityinfos.halkyon.io
spec:
  group: halkyon.io
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    kind: CapabilityInfo
    listKind: CapabilityInfoList
    plural: capabilityinfos
    singular: capabilityinfo
    shortNames:
      - capinfo
    categories:
      - all
  additionalPrinterColumns:
    - name: Category
      type: string
      description: "The category of the capability: database, logging, metric."
      JSONPath: .spec.category
    - name: Type
      type: string
      description: "The capability type for the given category. For a database category, that will be : postgres, mysql, ..."
      JSONPath: .spec.type
    - name: Supported versions
      type: string
      description: "The list of supported versions for the capability"
      JSONPath: .spec.versions
  scope: Cluster