apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runtimes.halkyon.io
spec:
  group: halkyon.io
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    kind: Runtime
    listKind: RuntimeList
    plural: runtimes
    singular: runtime
    categories:
      - all
  additionalPrinterColumns:
    - name: Runtime Name
      type: string
      JSONPath: .spec.name
    - name: Version
      type: string
      JSONPath: .spec.version
    - name: Image
      type: string
      JSONPath: .spec.image
  scope: Cluster