kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: halkyon-aggregate-admin-edit
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["halkyon.io"]
    resources: ["components", "components/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["halkyon.io"]
    resources: ["capabilities", "capabilities/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: halkyon-default-manage-capabilityinfos-runtimes
rules:
  - apiGroups: ["halkyon.io"]
    resources: ["capabilityinfos"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["halkyon.io"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]