/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/halkyonio/operator/pkg/apis/component/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCapabilities implements CapabilityInterface
type FakeCapabilities struct {
	Fake *FakeDevexpV1alpha2
	ns   string
}

var capabilitiesResource = schema.GroupVersionResource{Group: "devexp.runtime.redhat.com", Version: "v1alpha2", Resource: "capabilities"}

var capabilitiesKind = schema.GroupVersionKind{Group: "devexp.runtime.redhat.com", Version: "v1alpha2", Kind: "Capability"}

// Get takes name of the capability, and returns the corresponding capability object, and an error if there is any.
func (c *FakeCapabilities) Get(name string, options v1.GetOptions) (result *v1alpha2.Capability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(capabilitiesResource, c.ns, name), &v1alpha2.Capability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Capability), err
}

// List takes label and field selectors, and returns the list of Capabilities that match those selectors.
func (c *FakeCapabilities) List(opts v1.ListOptions) (result *v1alpha2.CapabilityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(capabilitiesResource, capabilitiesKind, c.ns, opts), &v1alpha2.CapabilityList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.CapabilityList{ListMeta: obj.(*v1alpha2.CapabilityList).ListMeta}
	for _, item := range obj.(*v1alpha2.CapabilityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested capabilities.
func (c *FakeCapabilities) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(capabilitiesResource, c.ns, opts))

}

// Create takes the representation of a capability and creates it.  Returns the server's representation of the capability, and an error, if there is any.
func (c *FakeCapabilities) Create(capability *v1alpha2.Capability) (result *v1alpha2.Capability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(capabilitiesResource, c.ns, capability), &v1alpha2.Capability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Capability), err
}

// Update takes the representation of a capability and updates it. Returns the server's representation of the capability, and an error, if there is any.
func (c *FakeCapabilities) Update(capability *v1alpha2.Capability) (result *v1alpha2.Capability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(capabilitiesResource, c.ns, capability), &v1alpha2.Capability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Capability), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCapabilities) UpdateStatus(capability *v1alpha2.Capability) (*v1alpha2.Capability, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(capabilitiesResource, "status", c.ns, capability), &v1alpha2.Capability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Capability), err
}

// Delete takes name of the capability and deletes it. Returns an error if one occurs.
func (c *FakeCapabilities) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(capabilitiesResource, c.ns, name), &v1alpha2.Capability{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCapabilities) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(capabilitiesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.CapabilityList{})
	return err
}

// Patch applies the patch and returns the patched capability.
func (c *FakeCapabilities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Capability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(capabilitiesResource, c.ns, name, pt, data, subresources...), &v1alpha2.Capability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Capability), err
}
