#
# TODO: TO be documented that we must configure such security rules on openshift
# oc adm policy add-scc-to-user privileged -z build-bot
# oc adm policy add-role-to-user edit -z build-bot
#
#
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: fruit-client-sb
spec:
  deploymentMode: build
  port: 8080
  buildConfig:
    url: https://github.com/snowdrop/component-operator-demo/
    ref: 0.0.2
    moduleDirName: fruit-client-sb
  runtime: spring-boot
  version: 2.1.3
  envs:
  - name: SPRING_PROFILES_ACTIVE
    value: openshift-catalog