#
# TODO: TO be documented that we must configure such security rules on openshift
# oc adm policy add-scc-to-user privileged -z build-bot
# oc adm policy add-role-to-user edit -z build-bot
#
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: http-rest-sb
spec:
  deploymentMode: build
  exposeService: true
  port: 8080
  buildConfig:
    type: "s2i"
    url: "https://github.com/snowdrop/rest-http-example.git"
    ref: "2.1.6-1"
    moduleDirName: "."
  runtime: spring-boot
  version: 2.1.6