/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	versioned "github.com/snowdrop/component-operator/pkg/apis/clientset/versioned"
	componentv1alpha2 "github.com/snowdrop/component-operator/pkg/apis/component/v1alpha2"
	internalinterfaces "github.com/snowdrop/component-operator/pkg/apis/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/snowdrop/component-operator/pkg/apis/listers/component/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CapabilityInformer provides access to a shared informer and lister for
// Capabilities.
type CapabilityInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.CapabilityLister
}

type capabilityInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCapabilityInformer constructs a new informer for Capability type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCapabilityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCapabilityInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCapabilityInformer constructs a new informer for Capability type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCapabilityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevexpV1alpha2().Capabilities(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevexpV1alpha2().Capabilities(namespace).Watch(options)
			},
		},
		&componentv1alpha2.Capability{},
		resyncPeriod,
		indexers,
	)
}

func (f *capabilityInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCapabilityInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *capabilityInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&componentv1alpha2.Capability{}, f.defaultInformer)
}

func (f *capabilityInformer) Lister() v1alpha2.CapabilityLister {
	return v1alpha2.NewCapabilityLister(f.Informer().GetIndexer())
}
